
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-diagram-generator
  labels:
    app: uml-diagram-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uml-diagram-generator
  template:
    metadata:
      labels:
        app: uml-diagram-generator
    spec:
      containers:
      - name: frontend
        image: ${DOCKER_REGISTRY}/uml-diagram-generator-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - mountPath: /data
            name: uml-data
      - name: backend
        image: ${DOCKER_REGISTRY}/uml-diagram-generator-backend:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - mountPath: /data
            name: uml-data
      volumes:
        - name: uml-data
          persistentVolumeClaim:
            claimName: uml-generator-data
